
## Author: Maarten L. Jung
## 
## Analyses and plots of the CRT predictions generated by the 
## Bayesian independence sampler

library(tidyr)
library(dplyr)
library(ggplot2)
library(ggh4x)
library(gtable)
library(cowplot)
library(see)
source("ma_thesis_helpers.R")

folder_data <- "data"
folder_fig <- "figures"
if (!dir.exists(folder_fig)) {
  dir.create(folder_fig)
}

# Analyses and plots of CRT predictions for simple combinations of proposal 
# distributions and likelihood functions =======================================

supp <- 1:99

disc_norm <- dnorm(supp, 50, 20)
disc_norm <- disc_norm / sum(disc_norm)
disc_unif <- rep(1/length(supp), length(supp))
disc_recinorm <- 1 / disc_norm
disc_recinorm <- disc_recinorm / sum(disc_recinorm)

kl_div(disc_norm, disc_norm)
kl_div(disc_unif, disc_norm)
kl_div(disc_norm, disc_recinorm)

d_prior_lik <- data.frame(x = supp, disc_norm, disc_unif, disc_recinorm) %>%
  gather(distribution, prob, -1)

p_prior_lik <- 
  ggplot(d_prior_lik, aes(x = x, y = prob, color = distribution)) +
  geom_point() + 
  scale_x_continuous(breaks = c(1, seq(10, 90, 10), 99)) + 
  scale_color_material(palette = "contrast") +
  ylab("Probability(x)") +
  labs(color = "Distribution") + 
  theme_bw() +
  theme(axis.text.y = element_text(size = 24),
        axis.text.x = element_text(size = 24),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_text(size = 28, face = "bold", 
                                    margin = margin(t = 0, r = 15, b = 0, l = 0)),
        axis.title.x = element_text(size = 28, face = "bold", 
                                    margin = margin(t = 10, r = 0, b = 0, l = 0)),
        
        legend.justification = c(1, 0), legend.position = c(0.9, 0.8),
        panel.spacing = unit(1, "lines"),
        legend.title = element_text(size = 24, face = "bold"),
        legend.text = element_text(size = 24),
        legend.background = element_rect(color = "black", 
                                         size = 0.5, 
                                         linetype = 1),
        legend.spacing.x = unit(0, "cm")) +
  guides(color = guide_legend(override.aes = list(size = 3)))

ggsave(file.path(folder_fig, "fig_prior_lik_generic_distr.svg"),
       p_prior_lik ,
       width = 5.7*2, height = 6*2)

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

d_normal_normal <- 
  read.csv(file.path(folder_data, 
                     "n_samples_prior_normal_lik_normal_all_ess_crits.csv"))

d_unif_normal <- 
  read.csv(file.path(folder_data, 
                     "n_samples_prior_unif_lik_normal_all_ess_crits.csv"))

d_normal_recinormal <- 
  read.csv(file.path(folder_data, 
                     "n_samples_prior_normal_lik_recinormal_all_ess_crits.csv"))

d_generic_distr <- lst(d_normal_normal, d_unif_normal, d_normal_recinormal) %>% 
  bind_rows(.id = "distribution") %>% 
  mutate_at("ess_criterion", factor) %>% 
  mutate(distribution = factor(distribution, levels = c("d_normal_normal", 
                                                        "d_unif_normal", 
                                                        "d_normal_recinormal")))
d_generic_distr %>% 
  group_by(ess_criterion, distribution) %>% 
  summarize(mean_n_omega = round(mean(n_samples)),
            median_n_omega = round(median(n_samples)),
            sigma_omega = round(sd(n_samples)),
            skew_omega = round(skewness(n_samples), 3),
            round(get_shiftlornm_standard_param(n_samples), 3),
            .groups = "drop") %>% 
  arrange(distribution, ess_criterion) %>% 
  knitr:::kable()

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

x_scales <- list(
  scale_x_continuous(breaks = seq(500, 1200, 175)),
  scale_x_continuous(breaks = seq(500, 1500, 250)),
  scale_x_continuous(breaks = seq(2000, 8000, 1500)),
  scale_x_continuous(breaks = seq(1000, 2000, 250)),
  scale_x_continuous(breaks = seq(1250, 2650, 350)),
  scale_x_continuous(breaks = seq(4500, 12500, 2000)),
  scale_x_continuous(breaks = seq(5500, 8300, 700)),
  scale_x_continuous(breaks = seq(7200, 10600, 850)),
  scale_x_continuous(breaks = seq(32000, 52000, 5000))
)

p_generic_distr_wrap <- 
  ggplot(d_generic_distr, mapping = aes(x = n_samples)) +
  facet_wrap(ess_criterion ~ distribution, ncol = 3, scales = "free") +
  geom_histogram(binwidth = freedman_diaconis, 
                 color = "black", 
                 fill = "white",
                 size = 0.5) + 
  geom_line(data = d_generic_distr %>%
              group_by(distribution, ess_criterion) %>%
              summarize(interpolate_shiftlnorm(n_samples),
                        .groups = "drop"),
            aes(x = x, y = y)) + 
  xlab("Number of samples to reach the ESS threshold \u03C9") +
  ylab("Count / scaled density") + 
  facetted_pos_scales(x = x_scales) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 20),
        axis.text.x = element_text(size = 20),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_text(size = 32, face = "bold", 
                                    margin = margin(t = 0, r = 18, b = 0, l = 0)),
        axis.title.x = element_text(size = 30, face = "bold", 
                                    margin = margin(t = 15, r = 0, b = 0, l = 0)),
        panel.spacing = unit(1, "lines"),
        strip.background = element_blank(),
        strip.text = element_blank())

ess_crit_labs <- c("\u03C9 = 500", "\u03C9 = 1000", "\u03C9 = 5000")
names(ess_crit_labs) <- c(500, 1000, 5000)

p_generic_distr_grid <- 
  ggplot(d_generic_distr, mapping = aes(x = n_samples)) +
  facet_grid(ess_criterion ~ distribution, scales = "free",
             labeller = labeller(ess_criterion = ess_crit_labs)) +
  theme_bw() +
  theme(strip.text.y = element_text(size = 30, face = "bold"))

# adds strip labels from facet_grid 
# hack adapted from https://stackoverflow.com/a/52708749

gt1 <- ggplot_gtable(ggplot_build(p_generic_distr_wrap))
gt2 <- ggplot_gtable(ggplot_build(p_generic_distr_grid))

gt.side1 <- gtable_filter(gt2, 'strip-r-1')
gt.side2 <- gtable_filter(gt2, 'strip-r-2')
gt.side3 <- gtable_filter(gt2, 'strip-r-3')

gt1 <- gtable_add_cols(gt1, widths = gt.side1$widths[1], pos = -1)
gt1 <- gtable_add_grob(gt1, zeroGrob(), t = 1, l = ncol(gt1), b = nrow(gt1))

panel_id <- gt1$layout[grep('panel-.+1$', gt1$layout$name), ]
gt1 <- gtable_add_grob(gt1, gt.side1, t = panel_id$t[1], l = ncol(gt1))
gt1 <- gtable_add_grob(gt1, gt.side2, t = panel_id$t[2], l = ncol(gt1))
gt1 <- gtable_add_grob(gt1, gt.side3, t = panel_id$t[3], l = ncol(gt1))

gt1 <- gtable_add_cols(gt1, widths = unit(1, "lines"), pos = -1)


ggsave(file.path(folder_fig, "fig_generic_distr.svg"),
       gt1,
       width = 10*2, height = 5.7*2)

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


# Analyses and plots of CRT predictions for the Bayesian habit-learning agent
# ==============================================================================

d_habit_distr <- 
  read.csv(file.path(folder_data, 
                     "n_samples_all_ess_crits_all_habit_tendcs.csv")) %>% 
  mutate_at(c("ess_criterion", "habitual_tendency"),
            factor) 

d_habit_distr %>% 
  mutate(third = case_when(episode %in% 1:16 ~ 1,
                           episode %in% 17:33 ~ 2,
                           episode %in% 34:50 ~ 3)) %>% 
  group_by(habitual_tendency, ess_criterion, third) %>% 
  summarize(mean_n_omega_thirds = round(mean(n_samples)),
            median_n_omega_thirds = round(median(n_samples)),
            .groups = "drop") %>% 
  left_join(d_habit_distr %>% 
              group_by(habitual_tendency, ess_criterion) %>% 
              summarize(mean_n_omega = round(mean(n_samples)),
                        median_n_omega = round(median(n_samples)),                     
                        sigma_omega = round(sd(n_samples)),
                        skew_omega = round(skewness(n_samples), 3),
                        round(get_shiftlornm_standard_param(n_samples), 3),
                        .groups = "drop"),
            by = c("habitual_tendency", "ess_criterion")) %>%
  arrange(ess_criterion, habitual_tendency) %>%
  knitr:::kable()

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

d_prior_lik_alpha_1 <- 
  read.csv(file.path(folder_data, "prior_lik_episode_50_alpha_1_world_52.csv"))

d_prior_lik_alpha_100 <- 
  read.csv(file.path(folder_data, "prior_lik_episode_50_alpha_100_world_13.csv"))

d_prior_lik <- rbind(d_prior_lik_alpha_1, d_prior_lik_alpha_100) %>% 
  mutate(habitual_tendency = factor(c(rep(1/1, nrow(d_prior_lik_alpha_1)), 
                                      rep(1/100, nrow(d_prior_lik_alpha_100))))) 

habit_labs <- c("Habitual tendency h = 0.01",
                "Habitual tendency h = 1")
names(habit_labs) <- c(0.01, 1)

p_policiy_prior_lik <- 
  ggplot(filter(d_prior_lik, policy_ind %in% 176:251),
         aes(x = policy_ind, y = prior_prob)) +
  facet_grid(. ~ habitual_tendency, labeller = labeller(habitual_tendency = habit_labs)) + 
  geom_point(aes(color = "Prior"), size = 2) + 
  geom_point(aes(y = norm_lik, color = "Likelihood"), size = 2) + 
  scale_color_manual(values = c(Prior = "#2196F3", Likelihood = "#F44336")) +
  geom_segment(data = filter(d_prior_lik, norm_lik > 0.1),
               aes(xend = policy_ind, 
                   y = prior_prob + 0.0008, yend = norm_lik - 0.0008),
               lineend = "round",
               linejoin = "bevel",
               arrow = arrow(length = unit(0.4, "cm")),
               size = 0.9,
               color = "#575757") + 
  ylab("Probability / normalized likelihood of policy j") +
  xlab("Policy index j") +
  labs(color = "Function") + 
  theme_bw() +
  theme(axis.text.y = element_text(size = 24),
        axis.text.x = element_text(size = 24),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_text(size = 30, face = "bold", 
                                    margin = margin(t = 0, r = 18, b = 0, l = 0)),
        axis.title.x = element_text(size = 28, face = "bold", 
                                    margin = margin(t = 15, r = 0, b = 0, l = 0)),
        legend.justification = c(1, 0), legend.position = c(0.85, 0.8),
        strip.text.x = element_text(size = 28, face = "bold"),
        panel.spacing = unit(1, "lines"),
        legend.title = element_text(size = 28, face = "bold"),
        legend.text = element_text(size = 24),
        legend.background = element_rect(color = "black", 
                                         size = 0.5, 
                                         linetype = 1),
        legend.spacing.x = unit(0, "cm")) +
  guides(color = guide_legend(override.aes = list(size = 3)))

ggsave(file.path(folder_fig, "fig_policies_prior_lik_similarity.svg"),
       p_policiy_prior_lik,
       width = 9*2, height = 6*2)

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

d_kl_div_prior_lik <- 
  read.csv(file.path(folder_data, "average_kl_div_alpha_1_10_100.csv")) %>% 
  mutate_at("habitual_tendency", factor)

p_kl_div_prior_lik <- 
  ggplot(d_kl_div_prior_lik, 
         aes(x = episode, y = kl_div, color = habitual_tendency)) +
  geom_point(size = 2) +
  scale_color_material(palette = "contrast") +
  scale_x_continuous(breaks = c(1, seq(10, 50, 10))) +
  xlab("Epsiode") + 
  ylab("Kullback-Leibler divergence") + 
  labs(color = "Habitual tendency") +
  theme_bw() +
  theme(axis.text.y = element_text(size = 24),
        axis.text.x = element_text(size = 24),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_text(size = 30, face = "bold", 
                                    margin = margin(t = 0, r = 18, b = 0, l = 0)),
        axis.title.x = element_text(size = 28, face = "bold", 
                                    margin = margin(t = 15, r = 0, b = 0, l = 0)),
        legend.justification = c(1, 0), legend.position = c(0.9, 0.6),
        legend.title = element_text(size = 28, face = "bold"),
        legend.text = element_text(size = 24),
        legend.background = element_rect(color = "black", 
                                         size = 0.5, 
                                         linetype = 1),
        legend.spacing.x = unit(0, "cm")) +
  guides(color = guide_legend(override.aes = list(size = 3))) 

ggsave(file.path(folder_fig, "fig_policies_kl_div_prior_lik.svg"),
       p_kl_div_prior_lik,
       width = 6*2, height = 4.5*2)

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

habit_labs <- c("Habitual tendency h = 0.01",
                "Habitual tendency h = 0.1",
                "Habitual tendency h = 1")
names(habit_labs) <- c(0.01, 0.1, 1)

p_habit_all_runs <- 
  ggplot(d_habit_distr, 
         mapping = aes(x = episode, y = n_samples, color = ess_criterion)) +
    facet_grid(. ~ habitual_tendency, 
               labeller = labeller(habitual_tendency = habit_labs)) +
    # set 95% coverage probability, i.e., the lower and upper limits of the 
    # vertical lines indicate the 2.5th and 97.5th percentiles 
    stat_summary(fun.data = median_hilow, fun.args = list(conf.int = 0.95), 
                 geom = "linerange") +
    stat_summary(fun = mean, geom = "point") +
    scale_color_material(palette = "contrast") + 
    scale_x_continuous(breaks = c(1, seq(10, 50, 10)),
                       minor_breaks = NULL) +
    scale_y_continuous(breaks = seq(0, 90000, 15000)) +
    xlab("Episode") + 
    labs(color = "ESS threshold \u03C9") +
    theme_bw() +
    theme(axis.text.y = element_text(size = 24),
          axis.text.x = element_text(size = 24),
          axis.ticks.y = element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          legend.justification = c(1, 0), legend.position = c(0.98, 0.8),
          panel.spacing = unit(1, "lines"),
          strip.text.x = element_text(size = 26, face = "bold"),
          legend.title = element_text(size = 24, face = "bold"),
          legend.text = element_text(size = 22),
          legend.background = element_rect(color = "black", 
                                           size = 0.5, 
                                           linetype = 1),
          legend.spacing.x = unit(0, "cm"))

p_habit_run_41 <- 
  ggplot(filter(d_habit_distr, repetition == 41), 
         mapping = aes(x = episode, y = n_samples, color = ess_criterion)) +
    facet_grid(. ~ habitual_tendency, 
               labeller = labeller(habitual_tendency = habit_labs)) +
    geom_point() +
    scale_color_material(palette = "contrast") + 
    scale_x_continuous(breaks = c(1, seq(10, 50, 10)),
                       minor_breaks = NULL) +
    scale_y_continuous(breaks = seq(0, 90000, 15000)) +
    ylab("Number of samples to reach \u03C9") +
    xlab("Episode") + 
    labs(color = "ESS threshold \u03C9") +
    theme_bw() +
    theme(axis.text.y = element_text(size = 24),
          axis.text.x = element_text(size = 24),
          axis.ticks.y = element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.y = element_text(size = 40, face = "bold", 
                                      margin = margin(t = 0, r = 18, b = 0, l = 0)),
          axis.title.x = element_text(size = 36, face = "bold", 
                                      margin = margin(t = 15, r = 0, b = 0, l = 0)),
          legend.justification = c(1, 0), legend.position = c(0.98, 0.8),
          panel.spacing = unit(1, "lines"),
          strip.text.x = element_text(size = 26, face = "bold"),
          legend.title = element_text(size = 24, face = "bold"),
          legend.text = element_text(size = 22),
          legend.background = element_rect(color = "black", 
                                           size = 0.5, 
                                           linetype = 1),
          legend.spacing.x = unit(0, "cm"))

p_habit_both <- plot_grid(ggplotGrob(p_habit_all_runs), 
                          ggplotGrob(p_habit_run_41), 
                          ncol = 1,
                          align = "v",
                          labels = c("A", "B"), label_size = 44)

ggsave(file.path(folder_fig, "fig_habit_point_est.svg"),
       p_habit_both ,
       width = 10*2, height = 10*2)

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

x_scales <- list(
  scale_x_continuous(breaks = seq(0, 70000, 10000)),
  scale_x_continuous(breaks = seq(0, 120000, 20000))
)

ess_crit_labs <- c("ESS criterion \u03C9 = 500", "ESS criterion \u03C9 = 1000")
names(ess_crit_labs) <- c(500, 1000)

p_habit_distr <-
  ggplot(d_habit_distr, aes(x = n_samples, fill = habitual_tendency)) +
    facet_grid(. ~ ess_criterion, scales = "free",
               labeller = labeller(ess_criterion = ess_crit_labs)) +
    geom_histogram(color = "black", 
                   alpha = 0.5,
                   size = 0.3,
                   binwidth = freedman_diaconis) + 
    geom_line(data = d_habit_distr %>%
                group_by(habitual_tendency, ess_criterion) %>%
                summarize(interpolate_shiftlnorm(n_samples, 201),
                          .groups = "drop"),
              aes(x = x, y = y),
              alpha = 0.55,
              size = 1.2) +
    scale_fill_material(palette = "contrast") + 
    scale_y_continuous(breaks = seq(0, 700, 100)) +
    facetted_pos_scales(x = x_scales) +
    xlab("Number of samples to reach the ESS threshold \u03C9") +
    ylab("Count / scaled density") + 
    labs(fill = "Habitual tendency h") +
    theme_bw() +
    theme(axis.text.y = element_text(size = 22),
          axis.text.x = element_text(size = 22),
          axis.ticks.y = element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.y = element_text(size = 30, face = "bold", 
                                      margin = margin(t = 0, r = 18, b = 0, l = 0)),
          axis.title.x = element_text(size = 28, face = "bold", 
                                      margin = margin(t = 16, r = 0, b = 0, l = 0)),
          legend.justification = c(1, 0), legend.position = c(0.98, 0.78),
          panel.spacing = unit(1, "lines"),
          strip.text.x = element_text(size = 24, face = "bold"),
          legend.title = element_text(size = 26, face = "bold"),
          legend.text = element_text(size = 24),
          legend.background = element_rect(color = "black", 
                                           size = 0.5, 
                                           linetype = 1))

ggsave(file.path(folder_fig, "fig_habit_distr.svg"),
       p_habit_distr,
       width = 10*2, height = 5.7*2)

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# > sessionInfo()
# R version 3.6.3 (2020-02-29)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 18363)
# 
# Matrix products: default
# 
# locale:
# [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
# [5] LC_TIME=German_Germany.1252    
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] gdtools_0.2.2      fitdistrplus_1.1-1 survival_3.1-8     MASS_7.3-51.5      see_0.6.0          cowplot_1.1.0      gtable_0.3.0       ggh4x_0.1.0.9000  
# [9] ggplot2_3.3.2      dplyr_1.0.2        tidyr_1.1.2       
# 
# loaded via a namespace (and not attached):
# [1]  tidyselect_1.1.0    xfun_0.17           purrr_0.3.4         splines_3.6.3       lattice_0.20-38     parameters_0.8.6    colorspace_1.4-1   
# [8]  vctrs_0.3.4         generics_0.0.2      htmltools_0.5.0     base64enc_0.1-3     rlang_0.4.7         pillar_1.4.6        foreign_0.8-75     
# [15] glue_1.4.2          withr_2.3.0         RColorBrewer_1.1-2  effectsize_0.3.3    jpeg_0.1-8.1        lifecycle_0.2.0     plyr_1.8.6         
# [22] stringr_1.4.0       munsell_0.5.0       bayestestR_0.7.2    htmlwidgets_1.5.1   labeling_0.3        latticeExtra_0.6-29 knitr_1.30         
# [29] htmlTable_2.1.0     highr_0.8           Rcpp_1.0.5          backports_1.1.10    checkmate_2.0.0     scales_1.1.1        Hmisc_4.4-1        
# [36] farver_2.0.3        systemfonts_0.3.2   gridExtra_2.3       png_0.1-7           digest_0.6.25       stringi_1.4.6       insight_0.9.6      
# [43] grid_3.6.3          tools_3.6.3         magrittr_1.5        tibble_3.0.3        Formula_1.2-3       cluster_2.1.0       crayon_1.3.4       
# [50] pkgconfig_2.0.3     ellipsis_0.3.1      Matrix_1.2-18       data.table_1.13.0   ggridges_0.5.2      svglite_1.2.3.2     rstudioapi_0.11    
# [57] R6_2.4.1            rpart_4.1-15        nnet_7.3-12         compiler_3.6.3  
